// <auto-generated />
using System;
using DataAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAPI.Migrations
{
    [DbContext(typeof(CurrencyDB))]
    [Migration("20230210130138_uptTables")]
    partial class uptTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataAPI.Models.CurrencyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AnnouncedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("BanknoteBuying")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BanknoteSelling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ForexBuying")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ForexSelling")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("currencyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
